# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.12.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.12.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/BartKim/Documents/workspace/sn3d-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/BartKim/Documents/workspace/sn3d-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.12.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.12.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/BartKim/Documents/workspace/sn3d-project/CMakeFiles /Users/BartKim/Documents/workspace/sn3d-project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/BartKim/Documents/workspace/sn3d-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Project

# Build rule for target.
Project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Project
.PHONY : Project

# fast build rule for target.
Project/fast:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/build
.PHONY : Project/fast

APP/APP_CONTROL.o: APP/APP_CONTROL.c.o

.PHONY : APP/APP_CONTROL.o

# target to build an object file
APP/APP_CONTROL.c.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_CONTROL.c.o
.PHONY : APP/APP_CONTROL.c.o

APP/APP_CONTROL.i: APP/APP_CONTROL.c.i

.PHONY : APP/APP_CONTROL.i

# target to preprocess a source file
APP/APP_CONTROL.c.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_CONTROL.c.i
.PHONY : APP/APP_CONTROL.c.i

APP/APP_CONTROL.s: APP/APP_CONTROL.c.s

.PHONY : APP/APP_CONTROL.s

# target to generate assembly for a file
APP/APP_CONTROL.c.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_CONTROL.c.s
.PHONY : APP/APP_CONTROL.c.s

APP/APP_FILE_SELECT.o: APP/APP_FILE_SELECT.c.o

.PHONY : APP/APP_FILE_SELECT.o

# target to build an object file
APP/APP_FILE_SELECT.c.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_FILE_SELECT.c.o
.PHONY : APP/APP_FILE_SELECT.c.o

APP/APP_FILE_SELECT.i: APP/APP_FILE_SELECT.c.i

.PHONY : APP/APP_FILE_SELECT.i

# target to preprocess a source file
APP/APP_FILE_SELECT.c.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_FILE_SELECT.c.i
.PHONY : APP/APP_FILE_SELECT.c.i

APP/APP_FILE_SELECT.s: APP/APP_FILE_SELECT.c.s

.PHONY : APP/APP_FILE_SELECT.s

# target to generate assembly for a file
APP/APP_FILE_SELECT.c.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_FILE_SELECT.c.s
.PHONY : APP/APP_FILE_SELECT.c.s

APP/APP_INIT.o: APP/APP_INIT.c.o

.PHONY : APP/APP_INIT.o

# target to build an object file
APP/APP_INIT.c.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_INIT.c.o
.PHONY : APP/APP_INIT.c.o

APP/APP_INIT.i: APP/APP_INIT.c.i

.PHONY : APP/APP_INIT.i

# target to preprocess a source file
APP/APP_INIT.c.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_INIT.c.i
.PHONY : APP/APP_INIT.c.i

APP/APP_INIT.s: APP/APP_INIT.c.s

.PHONY : APP/APP_INIT.s

# target to generate assembly for a file
APP/APP_INIT.c.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_INIT.c.s
.PHONY : APP/APP_INIT.c.s

APP/APP_MAIN.o: APP/APP_MAIN.c.o

.PHONY : APP/APP_MAIN.o

# target to build an object file
APP/APP_MAIN.c.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_MAIN.c.o
.PHONY : APP/APP_MAIN.c.o

APP/APP_MAIN.i: APP/APP_MAIN.c.i

.PHONY : APP/APP_MAIN.i

# target to preprocess a source file
APP/APP_MAIN.c.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_MAIN.c.i
.PHONY : APP/APP_MAIN.c.i

APP/APP_MAIN.s: APP/APP_MAIN.c.s

.PHONY : APP/APP_MAIN.s

# target to generate assembly for a file
APP/APP_MAIN.c.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_MAIN.c.s
.PHONY : APP/APP_MAIN.c.s

APP/APP_PAUSE.o: APP/APP_PAUSE.c.o

.PHONY : APP/APP_PAUSE.o

# target to build an object file
APP/APP_PAUSE.c.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_PAUSE.c.o
.PHONY : APP/APP_PAUSE.c.o

APP/APP_PAUSE.i: APP/APP_PAUSE.c.i

.PHONY : APP/APP_PAUSE.i

# target to preprocess a source file
APP/APP_PAUSE.c.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_PAUSE.c.i
.PHONY : APP/APP_PAUSE.c.i

APP/APP_PAUSE.s: APP/APP_PAUSE.c.s

.PHONY : APP/APP_PAUSE.s

# target to generate assembly for a file
APP/APP_PAUSE.c.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_PAUSE.c.s
.PHONY : APP/APP_PAUSE.c.s

APP/APP_PRINTING.o: APP/APP_PRINTING.c.o

.PHONY : APP/APP_PRINTING.o

# target to build an object file
APP/APP_PRINTING.c.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_PRINTING.c.o
.PHONY : APP/APP_PRINTING.c.o

APP/APP_PRINTING.i: APP/APP_PRINTING.c.i

.PHONY : APP/APP_PRINTING.i

# target to preprocess a source file
APP/APP_PRINTING.c.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_PRINTING.c.i
.PHONY : APP/APP_PRINTING.c.i

APP/APP_PRINTING.s: APP/APP_PRINTING.c.s

.PHONY : APP/APP_PRINTING.s

# target to generate assembly for a file
APP/APP_PRINTING.c.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_PRINTING.c.s
.PHONY : APP/APP_PRINTING.c.s

APP/APP_WAITING.o: APP/APP_WAITING.c.o

.PHONY : APP/APP_WAITING.o

# target to build an object file
APP/APP_WAITING.c.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_WAITING.c.o
.PHONY : APP/APP_WAITING.c.o

APP/APP_WAITING.i: APP/APP_WAITING.c.i

.PHONY : APP/APP_WAITING.i

# target to preprocess a source file
APP/APP_WAITING.c.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_WAITING.c.i
.PHONY : APP/APP_WAITING.c.i

APP/APP_WAITING.s: APP/APP_WAITING.c.s

.PHONY : APP/APP_WAITING.s

# target to generate assembly for a file
APP/APP_WAITING.c.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/APP/APP_WAITING.c.s
.PHONY : APP/APP_WAITING.c.s

MODUEL/SN_MODUEL_3D_PRINTER.o: MODUEL/SN_MODUEL_3D_PRINTER.c.o

.PHONY : MODUEL/SN_MODUEL_3D_PRINTER.o

# target to build an object file
MODUEL/SN_MODUEL_3D_PRINTER.c.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/MODUEL/SN_MODUEL_3D_PRINTER.c.o
.PHONY : MODUEL/SN_MODUEL_3D_PRINTER.c.o

MODUEL/SN_MODUEL_3D_PRINTER.i: MODUEL/SN_MODUEL_3D_PRINTER.c.i

.PHONY : MODUEL/SN_MODUEL_3D_PRINTER.i

# target to preprocess a source file
MODUEL/SN_MODUEL_3D_PRINTER.c.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/MODUEL/SN_MODUEL_3D_PRINTER.c.i
.PHONY : MODUEL/SN_MODUEL_3D_PRINTER.c.i

MODUEL/SN_MODUEL_3D_PRINTER.s: MODUEL/SN_MODUEL_3D_PRINTER.c.s

.PHONY : MODUEL/SN_MODUEL_3D_PRINTER.s

# target to generate assembly for a file
MODUEL/SN_MODUEL_3D_PRINTER.c.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/MODUEL/SN_MODUEL_3D_PRINTER.c.s
.PHONY : MODUEL/SN_MODUEL_3D_PRINTER.c.s

MODUEL/SN_MODUEL_DISPLAY.o: MODUEL/SN_MODUEL_DISPLAY.c.o

.PHONY : MODUEL/SN_MODUEL_DISPLAY.o

# target to build an object file
MODUEL/SN_MODUEL_DISPLAY.c.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/MODUEL/SN_MODUEL_DISPLAY.c.o
.PHONY : MODUEL/SN_MODUEL_DISPLAY.c.o

MODUEL/SN_MODUEL_DISPLAY.i: MODUEL/SN_MODUEL_DISPLAY.c.i

.PHONY : MODUEL/SN_MODUEL_DISPLAY.i

# target to preprocess a source file
MODUEL/SN_MODUEL_DISPLAY.c.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/MODUEL/SN_MODUEL_DISPLAY.c.i
.PHONY : MODUEL/SN_MODUEL_DISPLAY.c.i

MODUEL/SN_MODUEL_DISPLAY.s: MODUEL/SN_MODUEL_DISPLAY.c.s

.PHONY : MODUEL/SN_MODUEL_DISPLAY.s

# target to generate assembly for a file
MODUEL/SN_MODUEL_DISPLAY.c.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/MODUEL/SN_MODUEL_DISPLAY.c.s
.PHONY : MODUEL/SN_MODUEL_DISPLAY.c.s

MODUEL/SN_MODUEL_FILE_SYSTEM.o: MODUEL/SN_MODUEL_FILE_SYSTEM.c.o

.PHONY : MODUEL/SN_MODUEL_FILE_SYSTEM.o

# target to build an object file
MODUEL/SN_MODUEL_FILE_SYSTEM.c.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/MODUEL/SN_MODUEL_FILE_SYSTEM.c.o
.PHONY : MODUEL/SN_MODUEL_FILE_SYSTEM.c.o

MODUEL/SN_MODUEL_FILE_SYSTEM.i: MODUEL/SN_MODUEL_FILE_SYSTEM.c.i

.PHONY : MODUEL/SN_MODUEL_FILE_SYSTEM.i

# target to preprocess a source file
MODUEL/SN_MODUEL_FILE_SYSTEM.c.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/MODUEL/SN_MODUEL_FILE_SYSTEM.c.i
.PHONY : MODUEL/SN_MODUEL_FILE_SYSTEM.c.i

MODUEL/SN_MODUEL_FILE_SYSTEM.s: MODUEL/SN_MODUEL_FILE_SYSTEM.c.s

.PHONY : MODUEL/SN_MODUEL_FILE_SYSTEM.s

# target to generate assembly for a file
MODUEL/SN_MODUEL_FILE_SYSTEM.c.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/MODUEL/SN_MODUEL_FILE_SYSTEM.c.s
.PHONY : MODUEL/SN_MODUEL_FILE_SYSTEM.c.s

MODUEL/SN_MODUEL_IMAGE_VIEWER.o: MODUEL/SN_MODUEL_IMAGE_VIEWER.c.o

.PHONY : MODUEL/SN_MODUEL_IMAGE_VIEWER.o

# target to build an object file
MODUEL/SN_MODUEL_IMAGE_VIEWER.c.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/MODUEL/SN_MODUEL_IMAGE_VIEWER.c.o
.PHONY : MODUEL/SN_MODUEL_IMAGE_VIEWER.c.o

MODUEL/SN_MODUEL_IMAGE_VIEWER.i: MODUEL/SN_MODUEL_IMAGE_VIEWER.c.i

.PHONY : MODUEL/SN_MODUEL_IMAGE_VIEWER.i

# target to preprocess a source file
MODUEL/SN_MODUEL_IMAGE_VIEWER.c.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/MODUEL/SN_MODUEL_IMAGE_VIEWER.c.i
.PHONY : MODUEL/SN_MODUEL_IMAGE_VIEWER.c.i

MODUEL/SN_MODUEL_IMAGE_VIEWER.s: MODUEL/SN_MODUEL_IMAGE_VIEWER.c.s

.PHONY : MODUEL/SN_MODUEL_IMAGE_VIEWER.s

# target to generate assembly for a file
MODUEL/SN_MODUEL_IMAGE_VIEWER.c.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/MODUEL/SN_MODUEL_IMAGE_VIEWER.c.s
.PHONY : MODUEL/SN_MODUEL_IMAGE_VIEWER.c.s

SYSTEM/SN_SYS_INIT.o: SYSTEM/SN_SYS_INIT.c.o

.PHONY : SYSTEM/SN_SYS_INIT.o

# target to build an object file
SYSTEM/SN_SYS_INIT.c.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/SYSTEM/SN_SYS_INIT.c.o
.PHONY : SYSTEM/SN_SYS_INIT.c.o

SYSTEM/SN_SYS_INIT.i: SYSTEM/SN_SYS_INIT.c.i

.PHONY : SYSTEM/SN_SYS_INIT.i

# target to preprocess a source file
SYSTEM/SN_SYS_INIT.c.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/SYSTEM/SN_SYS_INIT.c.i
.PHONY : SYSTEM/SN_SYS_INIT.c.i

SYSTEM/SN_SYS_INIT.s: SYSTEM/SN_SYS_INIT.c.s

.PHONY : SYSTEM/SN_SYS_INIT.s

# target to generate assembly for a file
SYSTEM/SN_SYS_INIT.c.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/SYSTEM/SN_SYS_INIT.c.s
.PHONY : SYSTEM/SN_SYS_INIT.c.s

SYSTEM/SN_SYS_MESSAGE_Q.o: SYSTEM/SN_SYS_MESSAGE_Q.c.o

.PHONY : SYSTEM/SN_SYS_MESSAGE_Q.o

# target to build an object file
SYSTEM/SN_SYS_MESSAGE_Q.c.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/SYSTEM/SN_SYS_MESSAGE_Q.c.o
.PHONY : SYSTEM/SN_SYS_MESSAGE_Q.c.o

SYSTEM/SN_SYS_MESSAGE_Q.i: SYSTEM/SN_SYS_MESSAGE_Q.c.i

.PHONY : SYSTEM/SN_SYS_MESSAGE_Q.i

# target to preprocess a source file
SYSTEM/SN_SYS_MESSAGE_Q.c.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/SYSTEM/SN_SYS_MESSAGE_Q.c.i
.PHONY : SYSTEM/SN_SYS_MESSAGE_Q.c.i

SYSTEM/SN_SYS_MESSAGE_Q.s: SYSTEM/SN_SYS_MESSAGE_Q.c.s

.PHONY : SYSTEM/SN_SYS_MESSAGE_Q.s

# target to generate assembly for a file
SYSTEM/SN_SYS_MESSAGE_Q.c.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/SYSTEM/SN_SYS_MESSAGE_Q.c.s
.PHONY : SYSTEM/SN_SYS_MESSAGE_Q.c.s

SYSTEM/SN_SYS_SERIAL_COMM.o: SYSTEM/SN_SYS_SERIAL_COMM.c.o

.PHONY : SYSTEM/SN_SYS_SERIAL_COMM.o

# target to build an object file
SYSTEM/SN_SYS_SERIAL_COMM.c.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/SYSTEM/SN_SYS_SERIAL_COMM.c.o
.PHONY : SYSTEM/SN_SYS_SERIAL_COMM.c.o

SYSTEM/SN_SYS_SERIAL_COMM.i: SYSTEM/SN_SYS_SERIAL_COMM.c.i

.PHONY : SYSTEM/SN_SYS_SERIAL_COMM.i

# target to preprocess a source file
SYSTEM/SN_SYS_SERIAL_COMM.c.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/SYSTEM/SN_SYS_SERIAL_COMM.c.i
.PHONY : SYSTEM/SN_SYS_SERIAL_COMM.c.i

SYSTEM/SN_SYS_SERIAL_COMM.s: SYSTEM/SN_SYS_SERIAL_COMM.c.s

.PHONY : SYSTEM/SN_SYS_SERIAL_COMM.s

# target to generate assembly for a file
SYSTEM/SN_SYS_SERIAL_COMM.c.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/SYSTEM/SN_SYS_SERIAL_COMM.c.s
.PHONY : SYSTEM/SN_SYS_SERIAL_COMM.c.s

SYSTEM/SN_SYS_TIMER.o: SYSTEM/SN_SYS_TIMER.c.o

.PHONY : SYSTEM/SN_SYS_TIMER.o

# target to build an object file
SYSTEM/SN_SYS_TIMER.c.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/SYSTEM/SN_SYS_TIMER.c.o
.PHONY : SYSTEM/SN_SYS_TIMER.c.o

SYSTEM/SN_SYS_TIMER.i: SYSTEM/SN_SYS_TIMER.c.i

.PHONY : SYSTEM/SN_SYS_TIMER.i

# target to preprocess a source file
SYSTEM/SN_SYS_TIMER.c.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/SYSTEM/SN_SYS_TIMER.c.i
.PHONY : SYSTEM/SN_SYS_TIMER.c.i

SYSTEM/SN_SYS_TIMER.s: SYSTEM/SN_SYS_TIMER.c.s

.PHONY : SYSTEM/SN_SYS_TIMER.s

# target to generate assembly for a file
SYSTEM/SN_SYS_TIMER.c.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/SYSTEM/SN_SYS_TIMER.c.s
.PHONY : SYSTEM/SN_SYS_TIMER.c.s

SYSTEM/SN_SYS_USB_DRIVER.o: SYSTEM/SN_SYS_USB_DRIVER.c.o

.PHONY : SYSTEM/SN_SYS_USB_DRIVER.o

# target to build an object file
SYSTEM/SN_SYS_USB_DRIVER.c.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/SYSTEM/SN_SYS_USB_DRIVER.c.o
.PHONY : SYSTEM/SN_SYS_USB_DRIVER.c.o

SYSTEM/SN_SYS_USB_DRIVER.i: SYSTEM/SN_SYS_USB_DRIVER.c.i

.PHONY : SYSTEM/SN_SYS_USB_DRIVER.i

# target to preprocess a source file
SYSTEM/SN_SYS_USB_DRIVER.c.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/SYSTEM/SN_SYS_USB_DRIVER.c.i
.PHONY : SYSTEM/SN_SYS_USB_DRIVER.c.i

SYSTEM/SN_SYS_USB_DRIVER.s: SYSTEM/SN_SYS_USB_DRIVER.c.s

.PHONY : SYSTEM/SN_SYS_USB_DRIVER.s

# target to generate assembly for a file
SYSTEM/SN_SYS_USB_DRIVER.c.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/SYSTEM/SN_SYS_USB_DRIVER.c.s
.PHONY : SYSTEM/SN_SYS_USB_DRIVER.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Project"
	@echo "... APP/APP_CONTROL.o"
	@echo "... APP/APP_CONTROL.i"
	@echo "... APP/APP_CONTROL.s"
	@echo "... APP/APP_FILE_SELECT.o"
	@echo "... APP/APP_FILE_SELECT.i"
	@echo "... APP/APP_FILE_SELECT.s"
	@echo "... APP/APP_INIT.o"
	@echo "... APP/APP_INIT.i"
	@echo "... APP/APP_INIT.s"
	@echo "... APP/APP_MAIN.o"
	@echo "... APP/APP_MAIN.i"
	@echo "... APP/APP_MAIN.s"
	@echo "... APP/APP_PAUSE.o"
	@echo "... APP/APP_PAUSE.i"
	@echo "... APP/APP_PAUSE.s"
	@echo "... APP/APP_PRINTING.o"
	@echo "... APP/APP_PRINTING.i"
	@echo "... APP/APP_PRINTING.s"
	@echo "... APP/APP_WAITING.o"
	@echo "... APP/APP_WAITING.i"
	@echo "... APP/APP_WAITING.s"
	@echo "... MODUEL/SN_MODUEL_3D_PRINTER.o"
	@echo "... MODUEL/SN_MODUEL_3D_PRINTER.i"
	@echo "... MODUEL/SN_MODUEL_3D_PRINTER.s"
	@echo "... MODUEL/SN_MODUEL_DISPLAY.o"
	@echo "... MODUEL/SN_MODUEL_DISPLAY.i"
	@echo "... MODUEL/SN_MODUEL_DISPLAY.s"
	@echo "... MODUEL/SN_MODUEL_FILE_SYSTEM.o"
	@echo "... MODUEL/SN_MODUEL_FILE_SYSTEM.i"
	@echo "... MODUEL/SN_MODUEL_FILE_SYSTEM.s"
	@echo "... MODUEL/SN_MODUEL_IMAGE_VIEWER.o"
	@echo "... MODUEL/SN_MODUEL_IMAGE_VIEWER.i"
	@echo "... MODUEL/SN_MODUEL_IMAGE_VIEWER.s"
	@echo "... SYSTEM/SN_SYS_INIT.o"
	@echo "... SYSTEM/SN_SYS_INIT.i"
	@echo "... SYSTEM/SN_SYS_INIT.s"
	@echo "... SYSTEM/SN_SYS_MESSAGE_Q.o"
	@echo "... SYSTEM/SN_SYS_MESSAGE_Q.i"
	@echo "... SYSTEM/SN_SYS_MESSAGE_Q.s"
	@echo "... SYSTEM/SN_SYS_SERIAL_COMM.o"
	@echo "... SYSTEM/SN_SYS_SERIAL_COMM.i"
	@echo "... SYSTEM/SN_SYS_SERIAL_COMM.s"
	@echo "... SYSTEM/SN_SYS_TIMER.o"
	@echo "... SYSTEM/SN_SYS_TIMER.i"
	@echo "... SYSTEM/SN_SYS_TIMER.s"
	@echo "... SYSTEM/SN_SYS_USB_DRIVER.o"
	@echo "... SYSTEM/SN_SYS_USB_DRIVER.i"
	@echo "... SYSTEM/SN_SYS_USB_DRIVER.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

