/*
 * SN_MODUEL_IMAGE_VIEWER.h
 *
 *  Created on: 2018. 10. 1.
 *      Author: BartKim
 */

#ifndef MODUEL_INCLUDE_SN_MODUEL_IMAGE_VIEWER_H_
#define MODUEL_INCLUDE_SN_MODUEL_IMAGE_VIEWER_H_


extern SN_STATUS SN_MODULE_IMAGE_VIEWER_Init(void);
extern SN_STATUS SN_MODULE_IMAGE_VIEWER_Destroy(void);
extern SN_STATUS SN_MODULE_IMAGE_VIEWER_UPDATE(uint32_t sliceIndex);
extern SN_STATUS SN_MODULE_IMAGE_VIEWER_CLEAR(void);


#endif /* MODUEL_INCLUDE_SN_MODUEL_IMAGE_VIEWER_H_ */
