/*
 * SN_MODUEL_FILE_SYSTEM.h
 *
 *  Created on: 2018. 10. 1.
 *      Author: BartKim
 */

#ifndef MODUEL_INCLUDE_SN_MODUEL_FILE_SYSTEM_H_
#define MODUEL_INCLUDE_SN_MODUEL_FILE_SYSTEM_H_


#define MSG_FILE_SYSTEM_DETECTED    0
#define MSG_FILE_SYSTEM_READ        1
#define MSG_FILE_SYSTEM_UPDATE      2
#define MSG_FILE_SYSTEM_WAITING     3
#define MSG_FILE_SYSTEM_RESERVE     4

#define MSG_VALUE_FILE_SYSTEM_NONE 0

#endif /* MODUEL_INCLUDE_SN_MODUEL_FILE_SYSTEM_H_ */
